---
- hosts: k8s
  become: yes
  vars:
    docker_username: "{{ docker_username }}"
    version: "{{ version }}"

  tasks:
    - name: Asegurar que kubectl está disponible
      file:
        path: /usr/local/bin/kubectl
        state: link
        src: /var/lib/rancher/k3s/data/*/bin/kubectl
      ignore_errors: yes

    - name: Asegurar que el puerto 30000-32767 está abierto
      ufw:
        rule: allow
        port: 30000:32767
        proto: tcp

    - name: Crear namespace "CICD" (si no existe)
      shell: kubectl get namespace CICD || kubectl create namespace CICD

    - name: Marcar namespace como creado (bandera local)
      file:
        path: /tmp/k8s_namespace_CICD_created
        state: touch

  roles:
    - deploy_app