---
- name: Asegurar que kubectl está disponible
  file:
    path: /usr/local/bin/kubectl
    state: link
    src: /var/lib/rancher/k3s/data/*/bin/kubectl
  ignore_errors: yes

- name: Asegurar que el puerto 30000-32767 está abierto
  ufw:
    rule: allow
    port: 30000:32767
    proto: tcp

- name: Instalar pip para python3
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Instalar python3-kubernetes con apt
  apt:
    name: python3-kubernetes
    state: present

- name: Deploy PHP app Deployment
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: php-agenda
        labels:
          app: php-agenda
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: php-agenda
        template:
          metadata:
            labels:
              app: php-agenda
          spec:
            containers:
              - name: php-agenda
                image: "{{ docker_username }}/agenda:{{ version }}"
                ports:
                  - containerPort: 80
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 10

- name: Deploy PHP app Service (NodePort)
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: php-agenda-service
      spec:
        type: NodePort
        selector:
          app: php-agenda
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30080
