name: Despliegue de la app

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    runs-on: proyecto-integrado-asir
    environment: desarrollo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set commit SHA as version
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Docker Hub with token
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }} -f Implementacion/Aplicacion/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }}

      - name: Run Ansible playbook to deploy on Kubernetes node
        run: |
          ansible-playbook Implementacion\Ansible\playbooks\configurar_cluster.yml \
            -i Implementacion/infraestructura/inventario.ini \
            -e "version=${{ env.VERSION }} docker_username=${{ secrets.DOCKER_USERNAME }}"
