name: Despliegue de la app

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    name: Deploy en matriz de runners
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [aws-pi, proyecto-integrado-asir]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set commit SHA as version
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Docker Hub with token
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }} -f Implementacion/Aplicacion/Dockerfile Implementacion/Aplicacion
          docker push ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }}

      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > vault_pass.txt

      - name: Run Ansible playbook to deploy on Kubernetes node
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > vault_pass.txt
          export ANSIBLE_CONFIG=Implementacion/Ansible/ansible.cfg
          ansible-playbook -i Implementacion/Ansible/inventory.ini \
            Implementacion/Ansible/playbooks/configurar_cluster.yml \
            --vault-password-file vault_pass.txt \
            -e @Implementacion/Ansible/secrets.yml \
            -e "version=${{ env.VERSION }} docker_username=${{ secrets.DOCKER_USERNAME }}"
