name: Deploy app on push to testing

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    runs-on: proyecto-integrado-asir
    environment: desarrollo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set commit SHA as version
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Docker Hub with token
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }} -f Implementacion/Aplicacion/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/agenda:${{ env.VERSION }}

      - name: Generate deployment manifest
        run: |
          mkdir -p k8s
          sed "s/{{ version }}/${{ env.VERSION }}/g; s/{{ nodeport }}/30${{ env.VERSION }}/g" \
            Implementacion/Kubernetes/deployment-template.yml > Implementacion/Kubernetes/servicios/deployment-${{ env.VERSION }}.yml

      - name: Apply manifest (local runner ejecuta kubectl)
        run: kubectl apply -f Implementacion/Kubernetes/servicios/deployment-${{ env.VERSION }}.yml
